---
name: plex

releases:
- name: plex
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: plex
  instances: 1
  stemcell: default
  vm_type: default
  azs: [z1]
  persistent_disk_type: 2048
  networks:
  - name: default
  jobs:
  - name: plex
    release: plex

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
